{% set name = "des-despyastro" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DarkEnergySurvey/despyastro/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6d6c17a9961b1087ceb10463315e9ad5c3deaac2147c5fd3d6d37adca62ad41c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - scipy
    - esutil
    - matplotlib-base

test:
  requires:
    - python {{ python_min }}
  imports:
    - despyastro

about:
  home: https://github.com/DarkEnergySurvey/despymisc
  summary: 'A collection of astro-related Python functions useful for DESDM Python-based modules'
  license: NCSA
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - beckermr
